---
- name: NodeExporter - Get release
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ exporter_version }}/node_exporter-{{ exporter_version }}.{{ arch }}.tar.gz"
    dest: "{{ node_exporter_archive }}"
    mode: '0644'
  tags:
    - wordpress
    - exporter

- name: NodeExporter - Extract archive
  ansible.builtin.unarchive:
    src: "{{ node_exporter_archive }}"
    dest: "{{ tmp_path }}"
    remote_src: true
  tags:
    - wordpress
    - exporter

- name: NodeExporter - Copy binaries to "{{ bin_path }}"
  become: true
  ansible.builtin.copy:
    src: "{{ node_exporter_path_tmp }}/{{ item }}"
    dest: "{{ bin_path }}"
    remote_src: true
    mode: '0755'
  with_items:
    - node_exporter
  tags:
    - wordpress
    - exporter

- name: NodeExporter - Add Unit file
  become: true
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: "{{ systemd_path }}/node_exporter.service"
    mode: '644'
  notify:
    - Reload daemon
    - Start node_exporter
  tags:
    - wordpress
    - exporter

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Remove Artifacts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ node_exporter_archive }}"
    - "{{ node_exporter_path_tmp }}"
  tags:
    - wordpress
    - exporter
...
