---

- name: Check OS
  assert:
    that:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
    fail_msg: Host {{ ansible_hostname }} does not meet minimal reqs


- include_tasks: pretasks.yml
  tags: [always]

- include_tasks: yum.yml
  tags: [always]

- include_tasks: php.yml
  tags: [always]

- include_tasks: wordpress.yml
  tags: [always]

- include_tasks: exporter.yml
  tags: [always]
