---
- name: PHP - Copy config file
  become: true
  ansible.builtin.template:
    src: www.conf.j2
    dest: "{{ fpm_path }}/www.conf"
    mode: '644'
  tags:
    - wordpress
    - php

- name: PHP - Change group permission
  become: true
  ansible.builtin.file:
    path: "{{ php_path }}"
    state: directory
    recurse: true
    group: nginx
  notify:
    - Restart php-fpm
  tags:
    - wordpress
    - php

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
...
