---
- name: Yum - Upgrade packages
  become: true
  ansible.builtin.yum:
    name: "*"
    enablerepo: base,updates,extras
    state: present
    update_cache: true
  tags:
    - wordpress
    - yum

- name: Yum - Install packages
  become: true
  ansible.builtin.yum:
    name:
      - python36
    enablerepo: base,updates,extras
    state: present
  tags:
    - wordpress
    - yum

- name: Yum - Install EPEL
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
    state: present
  tags:
    - wordpress
    - yum

- name: Yum - Get Remi release
  ansible.builtin.get_url:
    url: "{{ repo_url }}"
    dest: "{{ rpm_package }}"
    mode: '0644'
  tags:
    - wordpress
    - yum

- name: Yum - Install Remi Repo
  become: true
  ansible.builtin.yum:
    name: "{{ rpm_package }}"
    state: present
  tags:
    - wordpress
    - yum

- name: Yum - edit yum.conf
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/yum.conf
    line: "http_caching=none"
  tags:
    - wordpress
    - yum

- name: Yum - Add Nginx Repo
  become: true
  ansible.builtin.template:
    src: nginx-stable.repo.j2
    dest: "{{ repo_path }}/nginx-stable.repo"
    mode: '644'
  tags:
    - wordpress
    - yum

- name: Yum - Install Nginx
  become: true
  ansible.builtin.yum:
    name:
      - nginx
    enablerepo: nginx-stable
    state: present
  tags:
    - wordpress
    - yum

- name: Yum - Install PHP & Git Packages
  become: true
  ansible.builtin.yum:
    name:
      - git
      - php
      - php-bz2
      - php-mysql
      - php-curl
      - php-gd
      - php-intl
      - php-common
      - php-mbstring
      - php-xml
      - php-cli
      - php-fpm
      - php-json
      - php-opcache
    enablerepo: base,remi-php72
    state: present
  tags:
    - wordpress
    - yum
...
